version: '2.0'

services:
  mysql:
    image: "mysql:5.7"
    container_name: mysqlnybble
    expose:
      - "3306"
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: "nybble"
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_USER: "nybble"
      MYSQL_PASSWORD: "nybble"
